name: Update GitHub Activity

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Activity
        uses: Readme-Workflows/activity@v2
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
