name: Update GitHub Activity

on:
  schedule:
    - cron: '0 */6 * * *'  # every 6 hours
  workflow_dispatch:

permissions:
  contents: write  # Allows writing to README.md

jobs:
  update-readme:
    name: Update GitHub Activity
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update README with GitHub activity
        uses: Readme-Workflows/activity@v2
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
