name: Update GitHub Activity

on:
  schedule:
    - cron: '0 */1 * * *'  # every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update README with recent GitHub activity
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: 5
          feed_list: "https://github.com/jfemon8"  # This can be any valid feed (see note below)
          custom_title: "📌 Latest GitHub Activity"
