name: Update GitHub Activity

on:
  schedule:
    - cron: '0 */1 * * *' # Every 1 hours
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Recent Activity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JamesIves/github-activity-readme@v0.2.0
        with:
          COMMIT_MSG: "Update recent GitHub activity"
